name: build
on:
  push:
    branches:
      - main
jobs:
  VeracodeContainer:
    runs-on: ubuntu-latest
    #needs: build
    steps:
      - name : CheckOut test
        uses: actions/checkout@v2

      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
          packages: >
            libc6-compat
            curl

      - name: Run Veracode Container
        env:
          VERACODE_API_KEY_ID: '${{ secrets.VID }}'
          VERACODE_API_KEY_SECRET: '${{ secrets.VKEY }}'
        run : |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode scan --source . --type directory --format table        
        shell: alpine.sh {0}