name: build
on:
  push:
    branches:
      - main
jobs:
  VeracodeContainer:
    runs-on: ubuntu-latest
    steps:
      - name : CheckOut test
        uses: actions/checkout@v2

      - name : Install packages
        run: sudo apt-get -qy install curl libc6

      - name: Run Veracode Container
        env:
          VERACODE_API_KEY_ID: '${{ secrets.VID }}'
          VERACODE_API_KEY_SECRET: '${{ secrets.VKEY }}'
        run : |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode scan --source . --type directory --format table --output results.txt

      - name: Save Contenair Results
        uses: actions/upload-artifact@v1
        with:
          name: ContainerResults
          path: results.txt